/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32g031xx.h"
#include "my_tims.h"

#define G031_MY_SYS_CLOCK	(uint16_t) 16000
#define TOGGLE_LDG 			GPIOC->ODR ^= GPIO_ODR_OD6

uint8_t my_tim16_irq = 0 ;
uint16_t tim16_arr = 0 ;
void ldg_init ( void ) ;

int main(void)
{
	ldg_init () ;
	config_my_tim16 ( G031_MY_SYS_CLOCK ) ;
	start_my_tim16 ( (uint16_t) 10000 ) ;
	while ( my_tim16_irq == 0 )
		;
	stop_my_tim16 () ;
	config_my_tim16 ( G031_MY_SYS_CLOCK ) ;
	start_my_tim16 ( (uint16_t) 1000 ) ;
	while  ( 1 )
		;
}

void ldg_init ( void ) // LDG = PC6
{
	RCC->IOPENR 	|=  RCC_IOPENR_GPIOCEN ;
	GPIOC->MODER 	|= 	GPIO_MODER_MODE6_0 ;
	GPIOC->MODER 	&= 	~GPIO_MODER_MODE6_1 ;
	GPIOC->OTYPER 	&= 	~GPIO_OTYPER_OT6 ;
	GPIOC->OSPEEDR 	&= 	~GPIO_OSPEEDR_OSPEED6 ;
	GPIOC->PUPDR 	&= 	~GPIO_PUPDR_PUPD6 ;
}

void reset_sr_uif_bit ( void )
{
	TIM16->CNT = (uint16_t) 0 ;
	TIM16->SR &= ~TIM_SR_UIF ;		// Clear IRQ flag
	TIM16->SR &= ~TIM_SR_CC1IF ; 	// CC1IF: Capture/Compare 1 interrupt flag
}

void TIM16_IRQHandler ( void )
{
	TOGGLE_LDG ;
	my_tim16_irq = 1 ;
	TIM16->SR &= ~TIM_SR_UIF ;		//Clean UIF Flag
}
